/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Audit */
        get: operations["queryAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Audit */
        post: operations["verifyAudit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Case */
        post: operations["openCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["addCaseMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["removeCaseMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Claim */
        post: operations["createClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim */
        get: operations["getClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Claim Provenance
         * @description Generic provenance for any claim-derived value (B-14).
         *
         *     Property values, aliases and edge labels all resolve to a claim, so one
         *     route serves every "where did this come from?" in the UI.
         */
        get: operations["claimProvenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Claim */
        post: operations["linkClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract Claim */
        post: operations["retractClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}/identity-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Identity History
         * @description The decision line behind an entity: who merged or split it, when, why.
         *
         *     Not gated on claim visibility: a decision records an adjudication, not the
         *     content of any source. Its note is written by the reviewer for exactly this
         *     audience (Article V, specs/06 §2.2).
         */
        get: operations["identityHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}/why-connected/{other_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Why Connected
         * @description Every claim this caller may see connecting two entities, with evidence.
         */
        get: operations["whyConnected"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Evidence */
        post: operations["registerEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}/custody-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Custody Event */
        post: operations["addCustodyEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Expand Graph
         * @description Breadth-first expansion from seeds, or the bounded overview without them.
         *
         *     POST rather than GET because the request is a query object — seed sets,
         *     category filters and time windows — not a resource address, and putting a
         *     hundred entity ids in a query string is how URL-length limits become silent
         *     truncation of an authorization-relevant input.
         */
        post: operations["expandGraph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Graph Paths
         * @description Shortest routes between two entities, bounded by hops and count.
         *
         *     A path here is a claim about *what the evidence connects*, not about what
         *     anyone did: every edge on it opens onto its claims, and none of them is
         *     graded by its position on the path (Article IX).
         */
        post: operations["graphPaths"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suggestions */
        get: operations["listSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-queue/{suggestion_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Suggestion */
        post: operations["acceptSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-queue/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Suggestion */
        post: operations["rejectSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Record */
        get: operations["getSourceRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-records/{record_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Record */
        post: operations["releaseSourceRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["listSources"];
        put?: never;
        /** Create Source */
        post: operations["createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptIn */
        AcceptIn: {
            /** Edits */
            edits?: {
                [key: string]: unknown;
            } | null;
            /** Note */
            note?: string | null;
        };
        /** AuditOut */
        AuditOut: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Case Id */
            case_id: string | null;
            /** Decision */
            decision: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Purpose */
            purpose: string | null;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: string | null;
        };
        /** CaseIn */
        CaseIn: {
            /**
             * Handling Code
             * @default open
             */
            handling_code?: string;
            /** Purpose */
            purpose: string;
            /** Title */
            title: string;
        };
        /** CaseMemberIn */
        CaseMemberIn: {
            /** Role */
            role: string;
            /** User Id */
            user_id: string;
        };
        /** CaseOut */
        CaseOut: {
            /** Case Id */
            case_id: string;
            /** Closed At */
            closed_at: string | null;
            /** Handling Code */
            handling_code: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Opened By */
            opened_by: string;
            /** Purpose */
            purpose: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** ClaimIn */
        ClaimIn: {
            /** Analytic Confidence */
            analytic_confidence?: string | null;
            /**
             * Assertion Type
             * @default reported
             */
            assertion_type?: string;
            /** Case Id */
            case_id?: string | null;
            /** Collection Method */
            collection_method?: string | null;
            /**
             * Credibility Normalized
             * @default cannot_judge
             */
            credibility_normalized?: string;
            /** Credibility Original */
            credibility_original?: string | null;
            /** Credibility Scheme */
            credibility_scheme?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /**
             * Handling Code
             * @default open
             */
            handling_code?: string;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Location Text */
            location_text?: string | null;
            /** Object Id */
            object_id?: string | null;
            /** Object Value */
            object_value?: unknown | null;
            /** Predicate */
            predicate: string;
            /** Record Id */
            record_id: string;
            /** Subject Id */
            subject_id: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Verification Status
             * @default unverified
             */
            verification_status?: string;
        };
        /** ClaimOut */
        ClaimOut: {
            /** Analytic Confidence */
            analytic_confidence: string | null;
            /** Assertion Type */
            assertion_type: string;
            /** Case Id */
            case_id: string | null;
            /** Claim Id */
            claim_id: string;
            /** Collection Method */
            collection_method: string | null;
            /** Credibility Normalized */
            credibility_normalized: string;
            /** Credibility Original */
            credibility_original: string | null;
            /** Credibility Scheme */
            credibility_scheme: string | null;
            /** Excerpt */
            excerpt: string | null;
            /** Handling Code */
            handling_code: string;
            /** Location Text */
            location_text: string | null;
            /** Object Id */
            object_id: string | null;
            /** Object Value */
            object_value: unknown | null;
            /** Ontology Version */
            ontology_version: string;
            /** Predicate */
            predicate: string;
            /** Record Id */
            record_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Retracted At */
            retracted_at: string | null;
            /** Retraction Reason */
            retraction_reason: string | null;
            /** Subject Id */
            subject_id: string;
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
            /** Verification Status */
            verification_status: string;
        };
        /**
         * ClaimProvenanceOut
         * @description One claim with its evidence — the unit the provenance panel renders.
         */
        ClaimProvenanceOut: {
            claim: components["schemas"]["ClaimOut"];
            /** Contradicted By */
            contradicted_by: string[];
            /** Corroborated By */
            corroborated_by: string[];
            grading: components["schemas"]["GradingOut"];
            object_mention: components["schemas"]["MentionOut"] | null;
            record: components["schemas"]["SourceRecordOut"] | null;
            source: components["schemas"]["SourceOut"] | null;
            subject_mention: components["schemas"]["MentionOut"] | null;
        };
        /** CustodyEventIn */
        CustodyEventIn: {
            /** From Actor */
            from_actor?: string | null;
            /**
             * Hash Checked
             * @default false
             */
            hash_checked?: boolean;
            /** Note */
            note?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Purpose */
            purpose: string;
            /** To Actor */
            to_actor: string;
        };
        /** EntityDetail */
        EntityDetail: {
            /** Claims By Predicate */
            claims_by_predicate: {
                [key: string]: components["schemas"]["ClaimOut"][];
            };
            entity: components["schemas"]["EntityOut"];
        };
        /** EntityOut */
        EntityOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
        };
        /** EvidenceIn */
        EvidenceIn: {
            /** Case Id */
            case_id?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Description */
            description: string;
            /**
             * Handling Code
             * @default restricted
             */
            handling_code?: string;
            /** Legal Basis */
            legal_basis?: string | null;
            /** Record Id */
            record_id?: string | null;
            /** Storage Uri */
            storage_uri?: string | null;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Acquired By */
            acquired_by: string | null;
            /** Case Id */
            case_id: string | null;
            /** Content Hash */
            content_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Evidence Id */
            evidence_id: string;
            /** Handling Code */
            handling_code: string;
            /** Record Id */
            record_id: string | null;
        };
        /**
         * GradingOut
         * @description The three dimensions, kept apart (Article III).
         *
         *     There is deliberately no combined score here. A single number would be the
         *     one thing every caller reached for, and it cannot be reconstructed back
         *     into the judgements that produced it.
         */
        GradingOut: {
            /** Analytic Confidence */
            analytic_confidence: string | null;
            /** Credibility */
            credibility: string;
            /** Reliability */
            reliability: string | null;
            /** Verification */
            verification: string;
        };
        /**
         * GraphEdgeOut
         * @description One time segment of one predicate — never a collapsed span (ADR-030).
         *
         *     There is no ``weight``. ``support`` carries each visible claim's three
         *     grading dimensions and the corroboration/contradiction counts around them,
         *     so a reader can reach the evidence instead of trusting a scalar.
         */
        GraphEdgeOut: {
            /** Category */
            category: string | null;
            /** Edge Id */
            edge_id: string;
            /** Object Id */
            object_id: string;
            /** Predicate */
            predicate: string;
            /** Record Count */
            record_count: number;
            /** Segment From */
            segment_from: string | null;
            /** Segment To */
            segment_to: string | null;
            /** Subject Id */
            subject_id: string;
            /** Support */
            support: {
                [key: string]: unknown;
            };
        };
        /**
         * GraphExpandIn
         * @description A bounded traversal request (specs/06 §2.6).
         *
         *     Every bound is clamped rather than rejected (specs/06 §4): a client asking
         *     for six hops gets three and is told the result was truncated, which is more
         *     useful than a 422 that teaches nothing about the limit.
         */
        GraphExpandIn: {
            /** Categories */
            categories?: string[];
            /**
             * Max Elements
             * @default 2000
             */
            max_elements?: number;
            /**
             * Max Hops
             * @default 1
             */
            max_hops?: number;
            /** Seed Ids */
            seed_ids?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
        };
        /** GraphPathOut */
        GraphPathOut: {
            /** Edge Ids */
            edge_ids: string[];
            /** Entity Ids */
            entity_ids: string[];
        };
        /** GraphPathsIn */
        GraphPathsIn: {
            /** Categories */
            categories?: string[];
            /** From Id */
            from_id: string;
            /**
             * Max Hops
             * @default 5
             */
            max_hops?: number;
            /**
             * Max Paths
             * @default 25
             */
            max_paths?: number;
            /** To Id */
            to_id: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** GraphPathsOut */
        GraphPathsOut: {
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Paths */
            paths: components["schemas"]["GraphPathOut"][];
            /** Resolved Seed Ids */
            resolved_seed_ids: string[];
            /** Seed Ids */
            seed_ids: string[];
            stamps: components["schemas"]["ProjectionStampsOut"] | null;
            /** Truncated */
            truncated: boolean;
        };
        /** GraphViewOut */
        GraphViewOut: {
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Resolved Seed Ids */
            resolved_seed_ids: string[];
            /** Seed Ids */
            seed_ids: string[];
            stamps: components["schemas"]["ProjectionStampsOut"] | null;
            /** Truncated */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityDecisionOut
         * @description A human's identity decision: who, when, why, and which revision.
         */
        IdentityDecisionOut: {
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Decided By */
            decided_by: string;
            /** Decision Id */
            decision_id: string;
            /** Decision Note */
            decision_note: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Kind */
            kind: string;
            /** Parent Revision Id */
            parent_revision_id: number;
            /** Result Revision Id */
            result_revision_id: number;
        };
        /**
         * MentionOut
         * @description The words a claim's argument came from (ADR-029).
         */
        MentionOut: {
            /** Char End */
            char_end: number | null;
            /** Char Start */
            char_start: number | null;
            /** Language */
            language: string | null;
            /** Mention Id */
            mention_id: string;
            /** Norm Key */
            norm_key: string;
            /** Raw Text */
            raw_text: string;
            /** Record Id */
            record_id: string;
            /** Script */
            script: string | null;
        };
        /**
         * ProjectionStampsOut
         * @description Which build produced these rows, and whether it is behind (specs/06 §3).
         */
        ProjectionStampsOut: {
            /** Active Revision Id */
            active_revision_id: number;
            /** Builder Version */
            builder_version: string | null;
            /** Built At Revision Id */
            built_at_revision_id: number | null;
            /** Ontology Version */
            ontology_version: string | null;
            /** Stale */
            stale: boolean;
        };
        /** RejectIn */
        RejectIn: {
            /** Reason */
            reason: string;
        };
        /** RelationIn */
        RelationIn: {
            /** Relation */
            relation: string;
            /** To Claim */
            to_claim: string;
        };
        /** RetractIn */
        RetractIn: {
            /** Reason */
            reason: string;
        };
        /** SourceIn */
        SourceIn: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Reliability Normalized */
            reliability_normalized?: string | null;
            /** Reliability Original */
            reliability_original?: string | null;
            /** Reliability Scheme */
            reliability_scheme?: string | null;
            /** Source Type */
            source_type: string;
            /** Url */
            url?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Name */
            name: string;
            /** Reliability Normalized */
            reliability_normalized: string | null;
            /** Source Id */
            source_id: string;
            /** Source Type */
            source_type: string;
            /** Url */
            url: string | null;
        };
        /** SourceRecordOut */
        SourceRecordOut: {
            /** Content Hash */
            content_hash: string;
            /** Handling Code */
            handling_code: string;
            /** Media Type */
            media_type: string | null;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Quarantine Reason */
            quarantine_reason: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Record Id */
            record_id: string;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
        };
        /** SuggestionOut */
        SuggestionOut: {
            /** Case Id */
            case_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Decision Note */
            decision_note: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Producer */
            producer: string;
            /** Producer Meta */
            producer_meta: {
                [key: string]: unknown;
            };
            /** Producer Version */
            producer_version: string;
            /** Record Id */
            record_id: string | null;
            /** Result Claim Id */
            result_claim_id: string | null;
            /** Result Decision Id */
            result_decision_id: string | null;
            /** Result Relation */
            result_relation: {
                [key: string]: unknown;
            } | null;
            /** Schema Version */
            schema_version: number;
            /** Status */
            status: string;
            /** Suggestion Id */
            suggestion_id: string;
            /** Suggestion Kind */
            suggestion_kind: string;
            /** Target Action */
            target_action: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WhyConnectedOut
         * @description The answer to GOAL.md §18 for one pair of entities.
         */
        WhyConnectedOut: {
            /** Claims */
            claims: components["schemas"]["ClaimProvenanceOut"][];
            /** Contradiction Count */
            contradiction_count: number;
            /** Corroboration Count */
            corroboration_count: number;
            /** Identity Line */
            identity_line: components["schemas"]["IdentityDecisionOut"][];
            /** Object Id */
            object_id: string;
            /** Record Count */
            record_count: number;
            /** Resolved Object Id */
            resolved_object_id: string;
            /** Resolved Subject Id */
            resolved_subject_id: string;
            /** Subject Id */
            subject_id: string;
            /** Truncated */
            truncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    queryAudit: {
        parameters: {
            query?: {
                actor?: string | null;
                case?: string | null;
                action?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verifyAudit: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    openCase: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCase: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addCaseMember: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseMemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeCaseMember: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createClaim: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getClaim: {
        parameters: {
            query?: {
                asOf?: string | null;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claimProvenance: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimProvenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    linkClaim: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retractClaim: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEntity: {
        parameters: {
            query?: {
                asOf?: string | null;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identityHistory: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityDecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whyConnected: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                other_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhyConnectedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registerEvidence: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEvidence: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addCustodyEvent: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustodyEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expandGraph: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphExpandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graphPaths: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphPathsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPathsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSuggestions: {
        parameters: {
            query?: {
                kind?: string | null;
                status?: string | null;
                producer?: string | null;
                record?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acceptSuggestion: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rejectSuggestion: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSourceRecord: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    releaseSourceRecord: {
        parameters: {
            query?: {
                note?: string;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSource: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
