/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Audit */
        get: operations["queryAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Audit */
        post: operations["verifyAudit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Case */
        post: operations["openCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Member */
        post: operations["addCaseMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["removeCaseMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Claim */
        post: operations["createClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim */
        get: operations["getClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Claim Provenance
         * @description Generic provenance for any claim-derived value (B-14).
         *
         *     Property values, aliases and edge labels all resolve to a claim, so one
         *     route serves every "where did this come from?" in the UI.
         */
        get: operations["claimProvenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Claim */
        post: operations["linkClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract Claim */
        post: operations["retractClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description One entity's claims, grouped by predicate, each with its evidence.
         *
         *     Grouping is what renders two disagreeing claims about the same property
         *     side by side; ``contradicted_by`` on each entry is what names the
         *     disagreement rather than leaving the reader to spot it (Article VIII).
         */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}/identity-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Identity History
         * @description The decision line behind an entity: who merged or split it, when, why.
         *
         *     Not gated on claim visibility: a decision records an adjudication, not the
         *     content of any source. Its note is written by the reviewer for exactly this
         *     audience (Article V, specs/06 §2.2).
         */
        get: operations["identityHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}/why-connected/{other_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Why Connected
         * @description Every claim this caller may see connecting two entities, with evidence.
         */
        get: operations["whyConnected"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Evidence */
        post: operations["registerEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/{evidence_id}/custody-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Custody Event */
        post: operations["addCustodyEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Expand Graph
         * @description Breadth-first expansion from seeds, or the bounded overview without them.
         *
         *     POST rather than GET because the request is a query object — seed sets,
         *     category filters and time windows — not a resource address, and putting a
         *     hundred entity ids in a query string is how URL-length limits become silent
         *     truncation of an authorization-relevant input.
         */
        post: operations["expandGraph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Graph Paths
         * @description Shortest routes between two entities, bounded by hops and count.
         *
         *     A path here is a claim about *what the evidence connects*, not about what
         *     anyone did: every edge on it opens onto its claims, and none of them is
         *     graded by its position on the path (Article IX).
         */
        post: operations["graphPaths"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidates
         * @description Machine-proposed pairs with their full explanation (spec 06 §2.2).
         */
        get: operations["listIdentityCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/candidates/batch-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Confirm
         * @description Confirm a pre-verified band — one ledger decision per pair (ADR-027).
         *
         *     Not one decision covering many pairs: each pair gets its own decision, its
         *     own revision and its own audit row, so a later reviewer can reverse one
         *     merge without unpicking the batch it arrived in.
         */
        post: operations["batchConfirmCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/identity/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Decision
         * @description Confirm, reject, split or mark unresolved — one action, one ledger row.
         *
         *     A stale ``parent_revision_id`` in the same entity scope raises
         *     ``StaleRevisionError``, which the app's error handler renders as a 409
         *     carrying the intervening decisions.
         */
        post: operations["recordIdentityDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Land Upload
         * @description Land an uploaded artifact (spec 04 §1 stage 1).
         */
        post: operations["landFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Land Text
         * @description Land pasted text (spec 04 §1 — "File / paste / curated entry").
         */
        post: operations["landText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ontology/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vocabulary
         * @description Closed vocabularies a caller needs to compose a valid request.
         *
         *     Authenticated but unrestricted by role: this is the shape of the domain,
         *     not anything asserted about anyone in it.
         */
        get: operations["getOntologyVocabulary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projections/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild Projections
         * @description Rebuild the edge projection from canonical claims.
         *
         *     Audited as an operator action (Article X). The report is returned rather
         *     than a bare 204 because "it rebuilt" is not the useful answer — how many
         *     endpoints were resolved through a mention anchor versus the canonical map
         *     is a live measure of how reversible the graph currently is.
         */
        post: operations["rebuildProjections"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suggestions */
        get: operations["listSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-queue/{suggestion_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Suggestion */
        post: operations["acceptSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review-queue/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Suggestion */
        post: operations["rejectSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Find entities by name, alias or the names they were mentioned under.
         *
         *     Authorization is applied while candidates are chosen, not after they are
         *     hydrated (ADR-012, B-17): an entity reachable only through claims above the
         *     caller's clearance is absent from the scan, so the result *count* cannot be
         *     used to infer that it exists.
         */
        get: operations["searchEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Source Records
         * @description Landed records the caller may see, newest first.
         *
         *     Rows above the caller's clearance are absent, not counted (specs/03 §4).
         */
        get: operations["listSourceRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Record */
        get: operations["getSourceRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-records/{record_id}/derivatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Derivatives
         * @description The transformations recorded for a record (spec 04 §1 stage 3).
         */
        get: operations["listDerivatives"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-records/{record_id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Record
         * @description Run an extraction pass over a record → review-queue suggestions.
         *
         *     Writes no claims (Article VII): everything produced here waits for
         *     ``review_suggestion``.
         */
        post: operations["extractRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-records/{record_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Record */
        post: operations["releaseSourceRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["listSources"];
        put?: never;
        /** Create Source */
        post: operations["createSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptIn */
        AcceptIn: {
            /** Edits */
            edits?: {
                [key: string]: unknown;
            } | null;
            /** Note */
            note?: string | null;
        };
        /** AuditOut */
        AuditOut: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Case Id */
            case_id: string | null;
            /** Decision */
            decision: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Purpose */
            purpose: string | null;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: string | null;
        };
        /** AuditPageOut */
        AuditPageOut: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** BatchConfirmIn */
        BatchConfirmIn: {
            /** Candidate Ids */
            candidate_ids: string[];
            /** Note */
            note: string;
            /** Parent Revision Id */
            parent_revision_id: number;
        };
        /**
         * BatchConfirmOut
         * @description One decision per confirmed pair (ADR-027), plus what was refused.
         *
         *     Partial rather than all-or-nothing, and the refusals are itemised. Two
         *     pairs in one batch can share an entity, in which case the second genuinely
         *     conflicts with the first — reporting that is more useful than either
         *     failing the batch or hiding it.
         */
        BatchConfirmOut: {
            /** Confirmed */
            confirmed: components["schemas"]["DecisionOut"][];
            /** Skipped */
            skipped: components["schemas"]["BatchSkipOut"][];
        };
        /** BatchSkipOut */
        BatchSkipOut: {
            /** Candidate Id */
            candidate_id: string;
            /** Reason */
            reason: string;
        };
        /** Body_landFile */
        Body_landFile: {
            /** Authority Ref */
            authority_ref?: string | null;
            /** Authority Valid From */
            authority_valid_from?: string | null;
            /** Authority Valid To */
            authority_valid_to?: string | null;
            /** Collection Policy */
            collection_policy?: string | null;
            /**
             * File
             * @description The artifact to land.
             */
            file: string;
            /**
             * Handling Code
             * @default open
             */
            handling_code?: string;
            /** Notes */
            notes?: string | null;
            /** Retention Class */
            retention_class?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /**
         * CandidateListOut
         * @description Candidates, plus the revision they were read at.
         *
         *     The revision travels with the list rather than through a separate lookup
         *     because that is what makes the concurrency check mean anything: a decision's
         *     ``parent_revision_id`` is meant to be *the state the analyst was looking at*
         *     when they decided. Fetching it independently would let a client send a
         *     revision newer than the screen it decided from, which is the exact race
         *     spec 05 §2 exists to catch.
         */
        CandidateListOut: {
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Revision Id */
            revision_id: number;
        };
        /**
         * CandidateMentionOut
         * @description One side of a candidate pair, with the context needed to judge it.
         *
         *     ``entity_id`` comes from the mention's *active* membership rather than the
         *     canonical map: a confirm moves memberships, so the active row is already
         *     the survivor. A pair whose sides were merged by an earlier decision
         *     therefore shows one entity on both sides, which is how an analyst tells
         *     "confirm this" from "already done".
         */
        CandidateMentionOut: {
            /** Entity Id */
            entity_id: string | null;
            /** Entity Label */
            entity_label: string | null;
            /** Language */
            language: string | null;
            /** Mention Id */
            mention_id: string;
            /** Norm Key */
            norm_key: string;
            /** Raw Text */
            raw_text: string;
            /** Record Id */
            record_id: string;
            /** Script */
            script: string | null;
        };
        /**
         * CandidateOut
         * @description A machine-proposed pair with its explanation (spec 06 §2.2).
         */
        CandidateOut: {
            /** Candidate Id */
            candidate_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Disposition */
            disposition: string;
            /** Features */
            features: {
                [key: string]: unknown;
            };
            /** Graph Snapshot Id */
            graph_snapshot_id: string | null;
            mention_a: components["schemas"]["CandidateMentionOut"];
            mention_b: components["schemas"]["CandidateMentionOut"];
            /** Pre Verified */
            pre_verified: boolean;
            /** Producer */
            producer: string;
            /** Producer Version */
            producer_version: string;
            /** Score */
            score: number | null;
        };
        /** CaseIn */
        CaseIn: {
            /**
             * Handling Code
             * @default open
             */
            handling_code?: string;
            /** Purpose */
            purpose: string;
            /** Title */
            title: string;
        };
        /** CaseMemberIn */
        CaseMemberIn: {
            /** Role */
            role: string;
            /** User Id */
            user_id: string;
        };
        /** CaseOut */
        CaseOut: {
            /** Case Id */
            case_id: string;
            /** Closed At */
            closed_at: string | null;
            /** Handling Code */
            handling_code: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Opened By */
            opened_by: string;
            /** Purpose */
            purpose: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** ClaimIn */
        ClaimIn: {
            /** Analytic Confidence */
            analytic_confidence?: string | null;
            /**
             * Assertion Type
             * @default reported
             */
            assertion_type?: string;
            /** Case Id */
            case_id?: string | null;
            /** Collection Method */
            collection_method?: string | null;
            /**
             * Credibility Normalized
             * @default cannot_judge
             */
            credibility_normalized?: string;
            /** Credibility Original */
            credibility_original?: string | null;
            /** Credibility Scheme */
            credibility_scheme?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /**
             * Handling Code
             * @default open
             */
            handling_code?: string;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Location Text */
            location_text?: string | null;
            /** Object Id */
            object_id?: string | null;
            /** Object Value */
            object_value?: unknown | null;
            /** Predicate */
            predicate: string;
            /** Record Id */
            record_id: string;
            /** Subject Id */
            subject_id: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Verification Status
             * @default unverified
             */
            verification_status?: string;
        };
        /** ClaimOut */
        ClaimOut: {
            /** Analytic Confidence */
            analytic_confidence: string | null;
            /** Assertion Type */
            assertion_type: string;
            /** Case Id */
            case_id: string | null;
            /** Claim Id */
            claim_id: string;
            /** Collection Method */
            collection_method: string | null;
            /** Credibility Normalized */
            credibility_normalized: string;
            /** Credibility Original */
            credibility_original: string | null;
            /** Credibility Scheme */
            credibility_scheme: string | null;
            /** Excerpt */
            excerpt: string | null;
            /** Handling Code */
            handling_code: string;
            /** Location Text */
            location_text: string | null;
            /** Object Id */
            object_id: string | null;
            /** Object Value */
            object_value: unknown | null;
            /** Ontology Version */
            ontology_version: string;
            /** Predicate */
            predicate: string;
            /** Record Id */
            record_id: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Retracted At */
            retracted_at: string | null;
            /** Retraction Reason */
            retraction_reason: string | null;
            /** Subject Id */
            subject_id: string;
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
            /** Verification Status */
            verification_status: string;
        };
        /**
         * ClaimProvenanceOut
         * @description One claim with its evidence — the unit the provenance panel renders.
         */
        ClaimProvenanceOut: {
            claim: components["schemas"]["ClaimOut"];
            /** Contradicted By */
            contradicted_by: string[];
            /** Corroborated By */
            corroborated_by: string[];
            grading: components["schemas"]["GradingOut"];
            object_mention: components["schemas"]["MentionOut"] | null;
            record: components["schemas"]["SourceRecordOut"] | null;
            source: components["schemas"]["SourceOut"] | null;
            subject_mention: components["schemas"]["MentionOut"] | null;
        };
        /** ConfirmMatchIn */
        ConfirmMatchIn: {
            /** Candidate Id */
            candidate_id?: string | null;
            /** Mention A */
            mention_a: string;
            /** Mention B */
            mention_b: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "confirm_match";
            /** Note */
            note: string;
            /** Parent Revision Id */
            parent_revision_id: number;
            /**
             * Protected Person
             * @default false
             */
            protected_person?: boolean;
        };
        /** CustodyEventIn */
        CustodyEventIn: {
            /** From Actor */
            from_actor?: string | null;
            /**
             * Hash Checked
             * @default false
             */
            hash_checked?: boolean;
            /** Note */
            note?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Purpose */
            purpose: string;
            /** To Actor */
            to_actor: string;
        };
        /**
         * DecisionOut
         * @description What an adjudication did, in enough detail to update a screen.
         */
        DecisionOut: {
            decision: components["schemas"]["IdentityDecisionOut"];
            /** Moved Mentions */
            moved_mentions: string[];
            /** New Entity Id */
            new_entity_id: string | null;
            /** Surviving Entity Id */
            surviving_entity_id: string | null;
            /** Unattributable Claims */
            unattributable_claims: string[];
        };
        /**
         * DerivativeOut
         * @description A recorded transformation (spec 04 §1 stage 3).
         */
        DerivativeOut: {
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Derivative Id */
            derivative_id: string;
            /** Kind */
            kind: string;
            /** Operator */
            operator: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Tool */
            tool: string;
            /** Tool Version */
            tool_version: string;
        };
        /**
         * EntityDetail
         * @description One entity's claims, grouped by predicate (spec 06 §2.1).
         *
         *     Each entry is a full ``ClaimProvenanceOut`` rather than a bare claim, so
         *     two claims disagreeing about the same property arrive already knowing they
         *     disagree. Grouping is what puts them side by side; ``contradicted_by`` is
         *     what stops the reader having to notice unaided (Article VIII).
         */
        EntityDetail: {
            /** Claims By Predicate */
            claims_by_predicate: {
                [key: string]: components["schemas"]["ClaimProvenanceOut"][];
            };
            entity: components["schemas"]["EntityOut"];
            /** Resolved Entity Id */
            resolved_entity_id: string;
            /**
             * Truncated
             * @default false
             */
            truncated?: boolean;
        };
        /**
         * EntityHitOut
         * @description One search result, with how it was found.
         */
        EntityHitOut: {
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
            /** Matched */
            matched: string;
            /** Score */
            score: number;
        };
        /** EntityOut */
        EntityOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
        };
        /** EvidenceIn */
        EvidenceIn: {
            /** Case Id */
            case_id?: string | null;
            /** Content Hash */
            content_hash?: string | null;
            /** Description */
            description: string;
            /**
             * Handling Code
             * @default restricted
             */
            handling_code?: string;
            /** Legal Basis */
            legal_basis?: string | null;
            /** Record Id */
            record_id?: string | null;
            /** Storage Uri */
            storage_uri?: string | null;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Acquired By */
            acquired_by: string | null;
            /** Case Id */
            case_id: string | null;
            /** Content Hash */
            content_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Evidence Id */
            evidence_id: string;
            /** Handling Code */
            handling_code: string;
            /** Record Id */
            record_id: string | null;
        };
        /** ExtractIn */
        ExtractIn: {
            /**
             * Mock
             * @description semantic only: run the offline deterministic extractor instead of a model. Output is labelled `model: mock` in producer_meta, so a suggestion never misrepresents what produced it.
             * @default false
             */
            mock?: boolean;
            /**
             * Producer
             * @default structural
             * @enum {string}
             */
            producer?: "structural" | "semantic";
        };
        /**
         * ExtractionOut
         * @description What one extraction run did — suggestions only, never claims (Article VII).
         */
        ExtractionOut: {
            derivative: components["schemas"]["DerivativeOut"] | null;
            /** Derivative Created */
            derivative_created: boolean;
            /** Producer */
            producer: string;
            /** Record Id */
            record_id: string;
            /** Suggestions Created */
            suggestions_created: number;
        };
        /**
         * GradingOut
         * @description The three dimensions, kept apart (Article III).
         *
         *     There is deliberately no combined score here. A single number would be the
         *     one thing every caller reached for, and it cannot be reconstructed back
         *     into the judgements that produced it.
         */
        GradingOut: {
            /** Analytic Confidence */
            analytic_confidence: string | null;
            /** Credibility */
            credibility: string;
            /** Reliability */
            reliability: string | null;
            /** Verification */
            verification: string;
        };
        /**
         * GraphEdgeOut
         * @description One time segment of one predicate — never a collapsed span (ADR-030).
         *
         *     There is no ``weight``. ``support`` carries each visible claim's three
         *     grading dimensions and the corroboration/contradiction counts around them,
         *     so a reader can reach the evidence instead of trusting a scalar.
         */
        GraphEdgeOut: {
            /** Category */
            category: string | null;
            /** Edge Id */
            edge_id: string;
            /** Object Id */
            object_id: string;
            /** Predicate */
            predicate: string;
            /** Record Count */
            record_count: number;
            /** Segment From */
            segment_from: string | null;
            /** Segment To */
            segment_to: string | null;
            /** Subject Id */
            subject_id: string;
            /** Support */
            support: {
                [key: string]: unknown;
            };
        };
        /**
         * GraphExpandIn
         * @description A bounded traversal request (specs/06 §2.6).
         *
         *     Every bound is clamped rather than rejected (specs/06 §4): a client asking
         *     for six hops gets three and is told the result was truncated, which is more
         *     useful than a 422 that teaches nothing about the limit.
         */
        GraphExpandIn: {
            /** Categories */
            categories?: string[];
            /**
             * Max Elements
             * @default 2000
             */
            max_elements?: number;
            /**
             * Max Hops
             * @default 1
             */
            max_hops?: number;
            /** Seed Ids */
            seed_ids?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Label */
            label: string;
        };
        /** GraphPathOut */
        GraphPathOut: {
            /** Edge Ids */
            edge_ids: string[];
            /** Entity Ids */
            entity_ids: string[];
        };
        /** GraphPathsIn */
        GraphPathsIn: {
            /** Categories */
            categories?: string[];
            /** From Id */
            from_id: string;
            /**
             * Max Hops
             * @default 5
             */
            max_hops?: number;
            /**
             * Max Paths
             * @default 25
             */
            max_paths?: number;
            /** To Id */
            to_id: string;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
        };
        /** GraphPathsOut */
        GraphPathsOut: {
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Paths */
            paths: components["schemas"]["GraphPathOut"][];
            /** Resolved Seed Ids */
            resolved_seed_ids: string[];
            /** Seed Ids */
            seed_ids: string[];
            stamps: components["schemas"]["ProjectionStampsOut"] | null;
            /** Truncated */
            truncated: boolean;
        };
        /** GraphViewOut */
        GraphViewOut: {
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Resolved Seed Ids */
            resolved_seed_ids: string[];
            /** Seed Ids */
            seed_ids: string[];
            stamps: components["schemas"]["ProjectionStampsOut"] | null;
            /** Truncated */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityDecisionOut
         * @description A human's identity decision: who, when, why, and which revision.
         */
        IdentityDecisionOut: {
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Decided By */
            decided_by: string;
            /** Decision Id */
            decision_id: string;
            /** Decision Note */
            decision_note: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Kind */
            kind: string;
            /** Parent Revision Id */
            parent_revision_id: number;
            /** Result Revision Id */
            result_revision_id: number;
        };
        /**
         * LandTextIn
         * @description A pasted note (spec 04 §1 — "File / paste / curated entry").
         *
         *     ``filename`` is not decoration: the ingest key is
         *     ``sha256(source_system | filename | content hash)``, so it is half of what
         *     makes re-pasting the same text under the same name a no-op, and it is what
         *     an operator will recognise the record by later.
         */
        LandTextIn: {
            /** Authority Ref */
            authority_ref?: string | null;
            /** Authority Valid From */
            authority_valid_from?: string | null;
            /** Authority Valid To */
            authority_valid_to?: string | null;
            /** Collection Policy */
            collection_policy?: string | null;
            /** Filename */
            filename: string;
            /**
             * Handling Code
             * @default open
             */
            handling_code?: string;
            /** Notes */
            notes?: string | null;
            /** Retention Class */
            retention_class?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Source Time */
            source_time?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Text */
            text: string;
        };
        /**
         * LandingOut
         * @description ``outcome`` is what *this request* did; ``record.status`` is what the
         *     record *is*.
         *
         *     They come apart on the case that matters: re-sending an artifact that
         *     landed quarantined is ``already_landed`` over a record whose status is
         *     ``quarantined``. Collapsing them would let a re-upload read as a fresh
         *     quarantine, or a no-op hide one.
         */
        LandingOut: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "landed" | "already_landed" | "quarantined";
            record: components["schemas"]["SourceRecordOut"];
        };
        /** MarkUnresolvedIn */
        MarkUnresolvedIn: {
            /** Candidate Id */
            candidate_id?: string | null;
            /** Mention A */
            mention_a: string;
            /** Mention B */
            mention_b: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "mark_unresolved";
            /** Note */
            note: string;
            /** Parent Revision Id */
            parent_revision_id: number;
            /**
             * Protected Person
             * @default false
             */
            protected_person?: boolean;
        };
        /**
         * MentionOut
         * @description The words a claim's argument came from (ADR-029).
         */
        MentionOut: {
            /** Char End */
            char_end: number | null;
            /** Char Start */
            char_start: number | null;
            /** Language */
            language: string | null;
            /** Mention Id */
            mention_id: string;
            /** Norm Key */
            norm_key: string;
            /** Raw Text */
            raw_text: string;
            /** Record Id */
            record_id: string;
            /** Script */
            script: string | null;
        };
        /**
         * OntologyVocabularyOut
         * @description Closed vocabularies, served so no client hand-writes them (Article XI).
         */
        OntologyVocabularyOut: {
            /** Assertion Types */
            assertion_types: string[];
            /** Handling Codes */
            handling_codes: string[];
            /** Source Types */
            source_types: string[];
            /** Version */
            version: string;
        };
        /**
         * ProjectionRebuildOut
         * @description What one rebuild produced (spec 06 §2.6, Article XIII).
         */
        ProjectionRebuildOut: {
            /** Anchor Resolved */
            anchor_resolved: number;
            /** Builder Version */
            builder_version: string;
            /** Built At Revision Id */
            built_at_revision_id: number;
            /** Claims Considered */
            claims_considered: number;
            /** Collapsed Endpoints */
            collapsed_endpoints: number;
            /** Edges */
            edges: number;
            /** Map Resolved */
            map_resolved: number;
            /** Ontology Version */
            ontology_version: string;
            /** Segments */
            segments: number;
        };
        /**
         * ProjectionStampsOut
         * @description Which build produced these rows, and whether it is behind (specs/06 §3).
         */
        ProjectionStampsOut: {
            /** Active Revision Id */
            active_revision_id: number;
            /** Builder Version */
            builder_version: string | null;
            /** Built At Revision Id */
            built_at_revision_id: number | null;
            /** Ontology Version */
            ontology_version: string | null;
            /** Stale */
            stale: boolean;
        };
        /** RejectIn */
        RejectIn: {
            /** Reason */
            reason: string;
        };
        /** RejectMatchIn */
        RejectMatchIn: {
            /** Candidate Id */
            candidate_id?: string | null;
            /** Evidence Basis */
            evidence_basis: string;
            /** Mention A */
            mention_a: string;
            /** Mention B */
            mention_b: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "reject_match";
            /** Note */
            note: string;
            /** Parent Revision Id */
            parent_revision_id: number;
            /**
             * Protected Person
             * @default false
             */
            protected_person?: boolean;
        };
        /** RelationIn */
        RelationIn: {
            /** Relation */
            relation: string;
            /** To Claim */
            to_claim: string;
        };
        /** RetractIn */
        RetractIn: {
            /** Reason */
            reason: string;
        };
        /** SearchResultsOut */
        SearchResultsOut: {
            /** Next Cursor */
            next_cursor?: string | null;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["EntityHitOut"][];
        };
        /** SourceIn */
        SourceIn: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Reliability Normalized */
            reliability_normalized?: string | null;
            /** Reliability Original */
            reliability_original?: string | null;
            /** Reliability Scheme */
            reliability_scheme?: string | null;
            /** Source Type */
            source_type: string;
            /** Url */
            url?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Name */
            name: string;
            /** Reliability Normalized */
            reliability_normalized: string | null;
            /** Source Id */
            source_id: string;
            /** Source Type */
            source_type: string;
            /** Url */
            url: string | null;
        };
        /** SourcePageOut */
        SourcePageOut: {
            /** Items */
            items: components["schemas"]["SourceOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SourceRecordOut */
        SourceRecordOut: {
            /** Authority Ref */
            authority_ref: string | null;
            /** Authority Valid From */
            authority_valid_from: string | null;
            /** Authority Valid To */
            authority_valid_to: string | null;
            /** Collection Policy Ref */
            collection_policy_ref: string | null;
            /** Content Hash */
            content_hash: string;
            /** Handling Code */
            handling_code: string;
            /** Media Type */
            media_type: string | null;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Quarantine Reason */
            quarantine_reason: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Record Id */
            record_id: string;
            /** Retention Class */
            retention_class: string | null;
            /** Source Id */
            source_id: string;
            /** Status */
            status: string;
        };
        /** SourceRecordPageOut */
        SourceRecordPageOut: {
            /** Items */
            items: components["schemas"]["SourceRecordOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SplitEntityIn */
        SplitEntityIn: {
            /** Entity Id */
            entity_id: string;
            /** Mention Ids */
            mention_ids: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "split_entity";
            /** Note */
            note: string;
            /** Parent Revision Id */
            parent_revision_id: number;
            /**
             * Protected Person
             * @default false
             */
            protected_person?: boolean;
            /** Target Entity Id */
            target_entity_id?: string | null;
        };
        /** SuggestionOut */
        SuggestionOut: {
            /** Case Id */
            case_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Decision Note */
            decision_note: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Producer */
            producer: string;
            /** Producer Meta */
            producer_meta: {
                [key: string]: unknown;
            };
            /** Producer Version */
            producer_version: string;
            /** Record Id */
            record_id: string | null;
            /** Result Claim Id */
            result_claim_id: string | null;
            /** Result Decision Id */
            result_decision_id: string | null;
            /** Result Relation */
            result_relation: {
                [key: string]: unknown;
            } | null;
            /** Schema Version */
            schema_version: number;
            /** Status */
            status: string;
            /** Suggestion Id */
            suggestion_id: string;
            /** Suggestion Kind */
            suggestion_kind: string;
            /** Target Action */
            target_action: string;
        };
        /** SuggestionPageOut */
        SuggestionPageOut: {
            /** Items */
            items: components["schemas"]["SuggestionOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WhyConnectedOut
         * @description The answer to GOAL.md §18 for one pair of entities.
         */
        WhyConnectedOut: {
            /** Claims */
            claims: components["schemas"]["ClaimProvenanceOut"][];
            /** Contradiction Count */
            contradiction_count: number;
            /** Corroboration Count */
            corroboration_count: number;
            /** Identity Line */
            identity_line: components["schemas"]["IdentityDecisionOut"][];
            /** Object Id */
            object_id: string;
            /** Record Count */
            record_count: number;
            /** Resolved Object Id */
            resolved_object_id: string;
            /** Resolved Subject Id */
            resolved_subject_id: string;
            /** Subject Id */
            subject_id: string;
            /** Truncated */
            truncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    queryAudit: {
        parameters: {
            query?: {
                actor?: string | null;
                case?: string | null;
                action?: string | null;
                from?: string | null;
                to?: string | null;
                cursor?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verifyAudit: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    openCase: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCase: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addCaseMember: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseMemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeCaseMember: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                case_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createClaim: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getClaim: {
        parameters: {
            query?: {
                asOf?: string | null;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claimProvenance: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimProvenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    linkClaim: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retractClaim: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEntity: {
        parameters: {
            query?: {
                asOf?: string | null;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identityHistory: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityDecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whyConnected: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
                other_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhyConnectedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registerEvidence: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getEvidence: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addCustodyEvent: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustodyEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expandGraph: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphExpandIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graphPaths: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphPathsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPathsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listIdentityCandidates: {
        parameters: {
            query?: {
                disposition?: string | null;
                producer?: string | null;
                cursor?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batchConfirmCandidates: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchConfirmOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordIdentityDecision: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMatchIn"] | components["schemas"]["RejectMatchIn"] | components["schemas"]["SplitEntityIn"] | components["schemas"]["MarkUnresolvedIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    landFile: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_landFile"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    landText: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LandTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOntologyVocabulary: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OntologyVocabularyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuildProjections: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionRebuildOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSuggestions: {
        parameters: {
            query?: {
                kind?: string | null;
                status?: string | null;
                producer?: string | null;
                record?: string | null;
                cursor?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acceptSuggestion: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rejectSuggestion: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    searchEntities: {
        parameters: {
            query: {
                /** @description Free-text name query */
                q: string;
                cursor?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSourceRecords: {
        parameters: {
            query?: {
                status?: string | null;
                source_id?: string | null;
                cursor?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRecordPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSourceRecord: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDerivatives: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivativeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extractRecord: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    releaseSourceRecord: {
        parameters: {
            query?: {
                note?: string;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSource: {
        parameters: {
            query?: {
                /** @description Reason for access */
                purpose?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
