"""Neo4j export: graph JSON -> executable Cypher file, or live push via the driver.

Vendored into the core by T21 (H-36): the platform must not import quarantined
prototype code, and an exporter is a generic algorithm rather than domain
scaffolding.

Two paths:
  - generate_cypher(graph): a self-contained .cypher file with literal MERGE
    statements. Because we know each edge's layer at generation time, the
    relationship TYPE is the layer (e.g. -[:FINANCIAL]->) with no APOC needed.
  - push_to_neo4j(graph, ...): parameterized UNWIND batches over the official
    driver.

A relationship type cannot be parameterized in Cypher, so it is interpolated —
and therefore has to be constrained.  The prototype constrained it with an
enum of the five criminal-network layers; a domain-neutral core cannot name
those (Article XIV), so the guard is now **structural**: a layer must look like
an identifier.  That is both domain-free and strictly stronger, since it holds
for ontology categories nobody has declared yet.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from collections import defaultdict
from pathlib import Path

#: A Cypher relationship type: upper-case identifier characters only. Anything
#: else — quotes, brackets, whitespace, backticks — cannot reach the query.
LAYER_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")


def _check_layer(layer: str) -> str:
    """Reject anything that is not a bare identifier, before interpolation."""
    if not isinstance(layer, str) or not LAYER_PATTERN.match(layer):
        raise ValueError(
            f"unsafe relationship type {layer!r} — refusing to emit; a layer "
            "must match " + LAYER_PATTERN.pattern
        )
    return layer


def _lit(value) -> str:
    """A JSON scalar/list as a Cypher literal (json.dumps escaping is Cypher-compatible)."""
    if value is None:
        return "null"
    return json.dumps(value, ensure_ascii=False)


def _date_lit(iso: str | None) -> str:
    return f'date("{iso}")' if iso else "null"


def generate_cypher(graph: dict) -> str:
    """Literal, idempotent Cypher for the whole graph (runs in Neo4j Browser as-is)."""
    lines: list[str] = [
        "// Auto-generated by pipeline.neo4j_export - idempotent (MERGE-based).",
        "CREATE CONSTRAINT criminal_node_id IF NOT EXISTS "
        "FOR (c:Criminal) REQUIRE c.node_id IS UNIQUE;",
        "",
    ]

    for n in graph["nodes"]:
        lines.append(
            f'MERGE (c:Criminal {{node_id: {_lit(n["node_id"])}}})\n'
            f"SET c.name = {_lit(n['name'])},\n"
            f"    c.aliases = {_lit(n.get('aliases', []))},\n"
            f"    c.nic = {_lit(n.get('nic'))},\n"
            f"    c.affiliations = {_lit(n.get('affiliations', []))},\n"
            f"    c.node_type = {_lit(n.get('node_type', 'PERSON'))},\n"
            f"    c.cluster_id = {_lit(n.get('cluster_id'))},\n"
            f"    c.source_file = {_lit(n.get('source_file', ''))},\n"
            f"    c.source_excerpt = {_lit(n.get('source_excerpt'))};"
        )
    lines.append("")

    for e in graph["edges"]:
        layer = _check_layer(e["layer"])
        lines.append(
            f'MATCH (a:Criminal {{node_id: {_lit(e["source"])}}})\n'
            f'MATCH (b:Criminal {{node_id: {_lit(e["target"])}}})\n'
            f"MERGE (a)-[r:{layer} {{relation: {_lit(e['relation'])}, "
            f"source_file: {_lit(e.get('source_file', ''))}}}]->(b)\n"
            f"SET r.confidence = {_lit(e['confidence'])},\n"
            f"    r.weight = {_lit(e['weight'])},\n"
            f"    r.start_date = {_date_lit(e.get('start_date'))},\n"
            f"    r.end_date = {_date_lit(e.get('end_date'))},\n"
            f"    r.location = {_lit(e.get('location'))},\n"
            f"    r.extraction_method = {_lit(e.get('extraction_method'))},\n"
            f"    r.source_excerpt = {_lit(e.get('source_excerpt'))};"
        )

    return "\n".join(lines) + "\n"


NODE_INGEST_QUERY = """
UNWIND $nodes AS n
MERGE (c:Criminal {node_id: n.node_id})
SET c.name = n.name,
    c.aliases = n.aliases,
    c.nic = n.nic,
    c.affiliations = n.affiliations,
    c.node_type = n.node_type,
    c.cluster_id = n.cluster_id,
    c.source_file = n.source_file,
    c.source_excerpt = n.source_excerpt
"""


def _edge_ingest_query(layer: str) -> str:
    _check_layer(layer)  # structural guard: a rel type is never free text
    return f"""
UNWIND $edges AS e
MATCH (a:Criminal {{node_id: e.source}})
MATCH (b:Criminal {{node_id: e.target}})
MERGE (a)-[r:{layer} {{relation: e.relation, source_file: coalesce(e.source_file, '')}}]->(b)
SET r.confidence = e.confidence,
    r.weight = e.weight,
    r.start_date = CASE WHEN e.start_date IS NULL THEN null ELSE date(e.start_date) END,
    r.end_date = CASE WHEN e.end_date IS NULL THEN null ELSE date(e.end_date) END,
    r.location = e.location,
    r.extraction_method = e.extraction_method,
    r.source_excerpt = e.source_excerpt
"""


def push_to_neo4j(
    graph: dict,
    uri: str | None = None,
    user: str | None = None,
    password: str | None = None,
    database: str = "neo4j",
) -> None:
    """Parameterized bulk ingest via the official driver (batched per layer)."""
    from neo4j import GraphDatabase  # lazy: optional dependency

    uri = uri or os.environ["NEO4J_URI"]
    user = user or os.getenv("NEO4J_USER", "neo4j")
    password = password or os.environ["NEO4J_PASSWORD"]

    by_layer: dict[str, list[dict]] = defaultdict(list)
    for e in graph["edges"]:
        by_layer[e["layer"]].append(e)

    with GraphDatabase.driver(uri, auth=(user, password)) as driver:
        with driver.session(database=database) as session:
            session.run(
                "CREATE CONSTRAINT criminal_node_id IF NOT EXISTS "
                "FOR (c:Criminal) REQUIRE c.node_id IS UNIQUE"
            )
            session.run(NODE_INGEST_QUERY, nodes=graph["nodes"])
            for layer, edges in by_layer.items():
                session.run(_edge_ingest_query(layer), edges=edges)
    print(f"Pushed {len(graph['nodes'])} nodes and {len(graph['edges'])} edges to {uri}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export graph JSON to Neo4j")
    parser.add_argument("--graph", default="output/graph.json")
    parser.add_argument("--out", default="output/ingest_generated.cypher")
    parser.add_argument("--push", action="store_true", help="also push via the neo4j driver (needs NEO4J_URI/PASSWORD)")
    args = parser.parse_args()

    graph = json.loads(Path(args.graph).read_text(encoding="utf-8"))
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(generate_cypher(graph), encoding="utf-8")
    print(f"Wrote {args.out}")
    if args.push:
        push_to_neo4j(graph)


if __name__ == "__main__":
    main()
