
"""Legacy migration tests (speckit T8).

Unit layer: the verb-remap table is exercised as a pure function over the
committed legacy graph JSON.  Integration layer (PostgreSQL): the full
migration must reconcile — 41 entities, every edge → ≥1 claim per the remap
table — and a re-run must change nothing.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from aegis.audit import verify
from aegis.evidence import LocalFilesystemVault
from aegis.migration import (
    CONFIDENCE_TAG_GRADING,
    VERB_REMAP,
    LegacyMigrationError,
    migrate,
    remap_edge,
    validate_legacy_maps,
)
from aegis.ontology import load
from aegis.store import (
    Claim,
    Entity,
    IdentityMembership,
    Mention,
    Source,
    SourceRecord,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
# The immutable committed legacy graph (57 edges). NOT output/real_graph.json —
# that file is regenerated by `aegis projections rebuild` into the *remapped*
# projection (63 edges), so reading it here would couple the test to whether a
# rebuild has run.
BASELINE = REPO_ROOT / "tests" / "snapshots" / "real_graph.baseline.json"
pytestmark = pytest.mark.requirement("Article-XIII", "T8")


@pytest.fixture(scope="module")
def ontology():
    return load(REPO_ROOT / "ontology" / "aegis.yaml")


@pytest.fixture(scope="module")
def baseline_graph() -> dict:
    return json.loads(BASELINE.read_text(encoding="utf-8"))


# ── unit: the remap table as a pure function ────────────────────────────────


def test_legacy_maps_validate_against_ontology(ontology) -> None:
    validate_legacy_maps(ontology)


def test_every_committed_edge_remaps(ontology, baseline_graph) -> None:
    """Migration AC: each edge → ≥1 claim; splits per the documented table."""
    total = 0
    for edge in baseline_graph["edges"]:
        drafts = remap_edge(edge, ontology)
        assert len(drafts) >= 1
        total += len(drafts)
    expected_splits = sum(
        1
        for edge in baseline_graph["edges"]
        if len(VERB_REMAP.get(edge["relation"], (None,))) > 1
    )
    assert total == len(baseline_graph["edges"]) + expected_splits


def test_compound_verbs_split_into_two_claims(ontology) -> None:
    edge = {
        "relation": "sibling_co_attacker_of",
        "confidence": "EXTRACTED",
        "layer": "IDEOLOGICAL",
        "start_date": None,
        "end_date": None,
        "location": None,
    }
    predicates = [d["predicate"] for d in remap_edge(edge, ontology)]
    assert predicates == ["sibling_of", "co_attacker_with"]
    assert all(d["split"] for d in remap_edge(edge, ontology))


def test_former_ally_splits_the_time_window(ontology) -> None:
    edge = {
        "relation": "former_ally_turned_rival_of",
        "confidence": "INFERRED",
        "layer": "FINANCIAL",
        "start_date": "2002-01-01",
        "end_date": None,
        "location": None,
    }
    allied, rival = remap_edge(edge, ontology)
    assert allied["predicate"] == "allied_with"
    assert (allied["valid_from"], allied["valid_to"]) == (None, "2002-01-01")
    assert rival["predicate"] == "rival_of"
    assert (rival["valid_from"], rival["valid_to"]) == ("2002-01-01", None)


def test_suspected_prefix_becomes_credibility_cap(ontology) -> None:
    edge = {
        "relation": "suspected_successor_leader_of",
        "confidence": "AMBIGUOUS",
        "layer": "IDEOLOGICAL",
        "start_date": None,
        "end_date": None,
        "location": None,
    }
    (draft,) = remap_edge(edge, ontology)
    assert draft["predicate"] == "successor_leader_of"
    assert draft["credibility_capped"] is True
    # AMBIGUOUS maps to 'doubtful', already weaker than the 'possibly_true' cap.
    assert draft["credibility_normalized"] == "doubtful"
    # An EXTRACTED "suspected" edge would be capped down to possibly_true.
    edge["confidence"] = "EXTRACTED"
    (capped,) = remap_edge(edge, ontology)
    assert capped["credibility_normalized"] == "possibly_true"


def test_location_moves_onto_the_claim(ontology) -> None:
    dubai = {
        "relation": "helped_establish_in_dubai",
        "confidence": "INFERRED",
        "layer": "TRANSNATIONAL",
        "start_date": None,
        "end_date": None,
        "location": "Dubai, UAE",
    }
    (draft,) = remap_edge(dubai, ontology)
    assert draft["predicate"] == "helped_establish_operations_of"
    # the edge's own location wins over the remap default
    assert draft["location_text"] == "Dubai, UAE"
    tamil = {
        "relation": "ran_narcotics_from_tamil_nadu_with",
        "confidence": "INFERRED",
        "layer": "TRANSNATIONAL",
        "start_date": None,
        "end_date": None,
        "location": None,
    }
    (draft,) = remap_edge(tamil, ontology)
    assert draft["predicate"] == "trafficked_narcotics_with"
    assert draft["location_text"] == "Tamil Nadu route"


def test_unknown_verb_fails_with_precise_error(ontology) -> None:
    edge = {
        "relation": "definitely_not_a_verb",
        "confidence": "EXTRACTED",
        "layer": "FINANCIAL",
    }
    with pytest.raises(LegacyMigrationError, match="predicates.definitely_not_a_verb"):
        remap_edge(edge, ontology)


def test_unknown_confidence_tag_fails(ontology) -> None:
    edge = {"relation": "member_of", "confidence": "GUESSED", "layer": "IDEOLOGICAL"}
    with pytest.raises(LegacyMigrationError, match="confidence.GUESSED"):
        remap_edge(edge, ontology)


def test_undeclared_category_correction_fails(ontology) -> None:
    # member_of is ideological; a FINANCIAL legacy layer is not a declared correction.
    edge = {"relation": "member_of", "confidence": "EXTRACTED", "layer": "FINANCIAL"}
    with pytest.raises(LegacyMigrationError, match="predicates.member_of.category"):
        remap_edge(edge, ontology)


def test_confidence_tag_map_matches_spec() -> None:
    assert CONFIDENCE_TAG_GRADING == {
        "EXTRACTED": ("confirmed", "record_confirmed"),
        "INFERRED": ("probably_true", "partially_corroborated"),
        "AMBIGUOUS": ("doubtful", "unverified"),
    }
